export const data = [
  {
    data: {
      search: {
        advert: {
          id: "202401105432219",
          stockItemId: "8a42d38f8cdaeae8018cf4702c2b1f50",
          isAuction: false,
          hoursUsed: null,
          serviceHistory: null,
          title: "Saab 9-3 1.9 TiD Vector Sport Auto Euro 4 4dr",
          excludePreviousOwners: false,
          advertisedLocations: [
            "at_cars",
            "at_dealer_partner_adverts",
            "at_profile",
            "at_profile_cars",
            "at_stock_cars",
            "retailer_websites",
            "trade_advertiser_stock",
          ],
          dueAtSeller: null,
          motExpiry: null,
          motInsurance: null,
          lastServiceOdometerReadingMiles: null,
          lastServiceDate: null,
          warrantyMonthsOnPurchase: null,
          twelveMonthsMotIncluded: false,
          heading: {
            title: "Saab 9-3",
            subtitle: "1.9 TiD Vector Sport Auto Euro 4 4dr",
            __typename: "Heading",
          },
          attentionGrabber: "FSH-C.CTRL-P.SNSR-DAB-BT-AUX",
          rrp: null,
          price: 2290,
          priceCurrency: "£",
          priceExcludingFees: 2290,
          suppliedPrice: 2290,
          suppliedPriceExcludingFees: 2290,
          priceOnApplication: false,
          plusVatIndicated: false,
          vatStatus: null,
          saving: null,
          noAdminFees: false,
          adminFee: null,
          adminFeeInfoDescription: null,
          dateOfRegistration: "2008-05-12",
          homeDeliveryRegionCodes: null,
          deliversToMyPostcode: null,
          capabilities: {
            marketExtensionHomeDelivery: null,
            marketExtensionClickAndCollect: null,
            marketExtensionCentrallyHeld: null,
            marketExtensionOem: null,
            sellerPromise: null,
            digitalRetailing: null,
            __typename: "Capabilities",
          },
          registration: "M****JX",
          encryptedRegistration: "hnmJwdUksK8dWU8yktwBdizq6tn58JY=",
          generation: {
            generationId: "fa47c713ecd3bdb381422d8243f9904c",
            name: "Saloon (2007 - 2011)",
            review: {
              ownerReviewsSummary: {
                aggregatedRating: 4.5,
                countOfReviews: 45,
                __typename: "OwnerReviewsSummary",
              },
              expertReviewSummary: {
                rating: 0,
                reviewUrl: "",
                __typename: "ExpertReviewSummary",
              },
              __typename: "GenerationReviewData",
            },
            __typename: "Generation",
          },
          hasShowroomProductCode: true,
          isPartExAvailable: true,
          isFinanceAvailable: true,
          isFinanceFullApplicationAvailable: false,
          financeProvider: "ZUTO",
          financeDefaults: {
            term: "48",
            mileage: "10000",
            depositAmount: "229",
            __typename: "FinanceDefaults",
          },
          retailerId: "10038946",
          hasClickAndCollect: false,
          privateAdvertiser: null,
          advertiserSegment: "Independent",
          dealer: {
            dealerId: "10038946",
            distance: null,
            stockLevels: {
              atStockCounts: {
                car: 64,
                van: null,
                __typename: "AtStockCounts",
              },
              __typename: "DealerStockLevels",
            },
            assignedNumber: {
              number: "+447451277214",
              __typename: "AssignedNumber",
            },
            awards: {
              isWinner2018: false,
              isWinner2019: false,
              isWinner2020: false,
              isWinner2021: false,
              isWinner2022: false,
              isWinner2023: false,
              isFinalist2018: false,
              isFinalist2019: false,
              isFinalist2020: false,
              isFinalist2021: false,
              isFinalist2022: false,
              isFinalist2023: false,
              isHighlyRated2018: false,
              isHighlyRated2019: false,
              isHighlyRated2020: false,
              isHighlyRated2021: false,
              isHighlyRated2022: false,
              isHighlyRated2023: false,
              __typename: "DealerAwards",
            },
            branding: {
              accreditations: [],
              brands: [],
              __typename: "DealerBranding",
            },
            capabilities: {
              instantMessagingChat: {
                enabled: true,
                provider: "VisitorChat",
                __typename: "InstantMessagingChatCapability",
              },
              instantMessagingText: {
                enabled: true,
                provider: "VisitorChat",
                overrideSmsNumber: "+447451277214",
                __typename: "InstantMessagingTextCapability",
              },
              __typename: "Capabilities",
            },
            reviews: {
              numberOfReviews: "20",
              overallReviewRating: "5.0",
              __typename: "Reviews",
            },
            location: {
              addressOne: "B&F NORTHAMPTON, Knightley Road",
              addressTwo: null,
              town: "Northampton",
              county: "Northamptonshire",
              postcode: "NN2 6HQ",
              latLong: "52.2521063,-0.9001935",
              __typename: "Location",
            },
            marketing: {
              profile: null,
              brandingBanner: {
                href: "https://m.atcdn.co.uk/dealer-logo/at2/adbranding/10038946/images/fpa_logo.gif",
                __typename: "Link",
              },
              __typename: "Marketing",
            },
            media: {
              email: "yes",
              dealerWebsite: {
                href: "http://bnfcarsnorthampton.co.uk/",
                __typename: "Link",
              },
              phoneNumber1: "(07915) 644624",
              phoneNumber2: null,
              protectedNumber: false,
              __typename: "DealerMedia",
            },
            name: "B&F Cars Northampton",
            servicesOffered: {
              sellerPromise: null,
              services: [],
              products: [
                "APXV",
                "AT18FINANCECUST",
                "AT18SELLCUST",
                "ATCRETAILESSENTIALS",
                "ATCRTLCHK",
                "ATCVVAL",
                "ATMOVES",
                "BOOST",
                "CHATVISITOR",
                "DVID",
                "FCS",
                "FPBARGAIN",
                "FPBONUS",
                "FPS",
                "ISP4VC",
                "ISSCUST",
                "ISS_PRODCAT",
                "PFIN",
                "PPI_4_ENHANCED",
                "PROFILE",
                "RTLCHKPLUS",
                "STEX",
                "VCHECKS",
                "WATC",
                "WAV",
                "WDEW",
                "WDPS",
                "WDSV",
                "WIMT",
                "WKSP",
                "WLGE",
                "WMPS",
                "WSDG",
                "WSL",
              ],
              safeSelling: null,
              homeDelivery: null,
              videoWalkAround: null,
              clickAndCollect: null,
              buyOnline: null,
              nccApproved: false,
              isHomeDeliveryProductEnabled: false,
              isPartExAvailable: true,
              hasSafeSelling: false,
              hasHomeDelivery: false,
              hasVideoWalkAround: false,
              additionalLinks: null,
              __typename: "ServicesOffered",
            },
            __typename: "Dealer",
          },
          video: null,
          spin: null,
          imageList: {
            nextCursor: null,
            size: 36,
            images: [
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/1185277ead9c445db62622a3046af5cb.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/938054d0758c403abf0d889f915baa62.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/e9514674a3504aecb5c0a6d6d2ee1530.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/ff5ef8e3f7f34568bf346f6aa229c7a4.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/d71ff00c6b8c4828b433e7bb2ab95df8.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/83e6c9534121452fbd88fc0c18e3cce0.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/eb6f9ce33bf54269a3697d79b744d9a7.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/8ba23a7cf86a4892a08852f2e108c151.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/3ff769dabb5949e185d930543d358c99.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/c1050e4686394c099f34f74d5784db85.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/377d4d00089c46d491407bd9adee0a92.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/c59949f1eb7b46ee882a17bcc95676e4.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/c2a2feeae95a42fd913e52c397c05b6b.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/0db9e41646a34d179c94bdf075a359bd.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/8d46f28c40a14eeb8d9fb92382f98ab5.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/5507171ae5624010be834f5fb13bf752.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/a63340655cc34abf9d6477b52eb737e3.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/ce203f7f292b459482c8f48ddd840cb9.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/05c6e4e0573f4e8280380ee9045baeb6.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/bc4d8bc71a6c4a4ea3618d14aba583c4.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/902768fbf1dc4c79bb08fa1eae9b2371.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/8134164382614a3293085344f6aec84d.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/23da4a22e3df44a7890170ab45162901.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/0b417543051c488c8b201ada88266273.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/11a0f4b386974247b7b8281845cfc184.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/987f9e3ecd0341c5ba3259fcba2f1575.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/55d4e42cd5d64b1f80e49cb72fdb4baf.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/153075c381c6425b8919ed822a862380.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/c7cc2d1b2e604ab9aa403239e460ba0a.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/435ae5458a5e4f2eabcfd5c46898a6d6.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/4439d74b804d4635adec22c23884758e.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/064a2c9d6fbf4a698a02489df26764cd.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/bd09bf5c1efd4764b287fbb61b98da23.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/028e9072ac2942dca18d7f9622f40746.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/a248d1523fc7451599b35802ba288d10.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
              {
                url: "https://m.atcdn.co.uk/a/media/{resize}/d83914d937624f5793fc3af92253bd3e.jpg",
                templated: true,
                autotraderAllocated: false,
                __typename: "ImageUrl",
              },
            ],
            __typename: "ImageList",
          },
          priceIndicatorRating: "NOANALYSIS",
          priceIndicatorRatingLabel: "",
          priceDeviation: null,
          mileageDeviation: null,
          mileage: {
            mileage: 152000,
            unit: "MILE",
            __typename: "Mileage",
          },
          plate: "08",
          year: 2008,
          vehicleCheckId: "05209faf7f2c4f8ca00776cb9b7f72d8",
          vehicleCheckStatus: "PASSED",
          vehicleCheckSummary: {
            type: "FULL",
            title: "All checks passed",
            performed: "2024-01-10",
            writeOffCategory: null,
            checks: [
              {
                key: "STOLEN",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "SCRAPPED",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "WRITE_OFF_CATEGORY",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "IMPORTED",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "EXPORTED",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "HIGH_RISK",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "MILEAGE_DISCREPANCY",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "COLOUR_CHANGED",
                failed: false,
                advisory: false,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "PRIVATE_FINANCE",
                failed: false,
                advisory: true,
                critical: true,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "TRADE_FINANCE",
                failed: false,
                advisory: false,
                critical: false,
                warning: false,
                __typename: "VehicleCheck",
              },
              {
                key: "REGISTRATION_CHANGED",
                failed: false,
                advisory: false,
                critical: true,
                warning: true,
                __typename: "VehicleCheck",
              },
            ],
            __typename: "VehicleCheckSummary",
          },
          sellerName: "B&F Cars Northampton",
          sellerType: "Trade",
          sellerProducts: [
            "APXV",
            "AT18FINANCECUST",
            "AT18SELLCUST",
            "ATCRETAILESSENTIALS",
            "ATCRTLCHK",
            "ATCVVAL",
            "ATMOVES",
            "BOOST",
            "CHATVISITOR",
            "DVID",
            "FCS",
            "FPBARGAIN",
            "FPBONUS",
            "FPS",
            "ISP4VC",
            "ISSCUST",
            "ISS_PRODCAT",
            "PFIN",
            "PPI_4_ENHANCED",
            "PROFILE",
            "RTLCHKPLUS",
            "STEX",
            "VCHECKS",
            "WATC",
            "WAV",
            "WDEW",
            "WDPS",
            "WDSV",
            "WIMT",
            "WKSP",
            "WLGE",
            "WMPS",
            "WSDG",
            "WSL",
          ],
          sellerLocation: "NORTHAMPTON",
          sellerLocationDistance: null,
          sellerContact: {
            phoneNumberOne: "(07915) 644624",
            phoneNumberTwo: null,
            protectedNumber: null,
            byEmail: true,
            __typename: "SellerContact",
          },
          description:
            "DRIVES VERY GOOD |  SERVICE HISTORY | CRUISE CONTROL | PARKING SENSOR | DAB RADIO | FULL LEATHER SEATS | BLUETOOTH | AUX | USB | CLIMET CONTROL | 17in 5 SPOKE  ALLOY  WHEELS, Finance available at very affordable rates (Subject to status & vehicle age/mileage) | First to see will definitely buy | Drives like a brand new car | We also offer comprehensive warranties over a variety of different terms (The warranty is extendable, up to 4 years)  | 12 months free AA breakdown cover | 12 months fresh  MOT (If the mot expires within next 3 months) | 5 days drive away insurance available | Full dealer facilities available | If you are coming by train, We can pick you up from the nearest station | We are open 7 days a week | Every effort has been made to ensure the accuracy of the above information but please be aware that the errors may occur | If you are looking for specific specs, please feel free to give us a call, We specialize in the sales of quality used cars at extremely competitive and affordable prices. A trusted dealership with 15 years of experience makes us a perfect place to visit for your next car. We take pride in presenting our customers with a fantastic range of cars and always do our very best to satisfy you with our excellent customer service before and after a sale. Please read our reviews and call us now to arrange an appointment! , Good bodywork, Black Full leather interior - Good Condition, Tyre condition Good, Silver, £2,290",
          colour: "Silver",
          manufacturerApproved: false,
          insuranceWriteOffCategory: null,
          owners: null,
          vehicleCondition: {
            tyreCondition: 85,
            interiorCondition: 65,
            bodyCondition: 65,
            __typename: "VehicleCondition",
          },
          specification: {
            isCrossover: false,
            operatingType: null,
            emissionClass: "Euro 4",
            co2Emissions: {
              co2Emission: 177,
              unit: "g/km",
              __typename: "Co2Emissions",
            },
            topSpeed: {
              topSpeed: 131,
              __typename: "Speed",
            },
            minimumKerbWeight: {
              weight: null,
              unit: null,
              __typename: "Weight",
            },
            endLayout: null,
            trailerAxleNumber: null,
            bedroomLayout: null,
            grossVehicleWeight: {
              weight: null,
              unit: null,
              __typename: "Weight",
            },
            capacityWeight: {
              weight: null,
              unit: null,
              __typename: "Weight",
            },
            liftingCapacity: {
              weight: null,
              unit: null,
              __typename: "LiftingCapacity",
            },
            operatingWidth: {
              width: null,
              unit: null,
              __typename: "OperatingWidth",
            },
            maxReach: {
              length: null,
              unit: null,
              __typename: "MaxReach",
            },
            wheelbase: "STD",
            berth: null,
            bedrooms: null,
            engine: {
              power: {
                enginePower: 150,
                unit: "PS",
                __typename: "Power",
              },
              sizeLitres: 1.9,
              sizeCC: 1910,
              manufacturerEngineSize: 1.9,
              __typename: "Engine",
            },
            exteriorWidth: {
              width: 2038,
              unit: "mm",
              __typename: "ExteriorWidth",
            },
            exteriorLength: {
              length: 4647,
              unit: "mm",
              __typename: "ExteriorLength",
            },
            exteriorHeight: {
              height: 1473,
              unit: "mm",
              __typename: "ExteriorHeight",
            },
            capacityWidth: {
              width: null,
              unit: null,
              __typename: "CapacityWidth",
            },
            capacityLength: {
              length: null,
              unit: null,
              __typename: "CapacityLength",
            },
            capacityHeight: {
              height: null,
              unit: null,
              __typename: "CapacityHeight",
            },
            seats: 5,
            axleConfig: null,
            ulezCompliant: false,
            doors: 4,
            bodyType: "Saloon",
            cabType: "Unlisted",
            rawBodyType: "Saloon",
            fuel: "Diesel",
            transmission: "Automatic",
            style: null,
            subStyle: null,
            make: "Saab",
            model: "9-3",
            trim: "Vector Sport",
            vehicleCategory: "Car",
            optionalFeatures: null,
            standardFeatures: [
              {
                description: "17in 5Spoke Alloy Wheels",
                category: "Standard",
                __typename: "Feature",
              },
              {
                description: "17in 5Spoke Split Alloy Wheels",
                category: "Standard",
                __typename: "Feature",
              },
              {
                description: "Lowered Sport chassis",
                category: "Standard",
                __typename: "Feature",
              },
              {
                description: "Metal finish Trim",
                category: "Standard",
                __typename: "Feature",
              },
            ],
            driverPosition: "RHD",
            battery: null,
            techData: {
              co2Emissions: "177 g/km",
              fuelConsumptionCombined: "42.80 mpg",
              fuelConsumptionExtraUrban: "56.50 mpg",
              fuelConsumptionUrban: "30.10 mpg",
              insuranceGroup: "24E",
              minimumKerbWeight: "3 kg",
              zeroToSixtyMph: null,
              zeroToSixtyTwoMph: "11.00 seconds",
              cylinders: "4",
              valves: "16",
              enginePower: "148 bhp",
              topSpeed: "131 mph",
              engineTorque: "236.00 lbs/ft",
              vehicleHeight: "1000 mm",
              vehicleLength: "4647 mm",
              vehicleWidth: "2038 mm",
              wheelbase: "2675 mm",
              fuelTankCapacity: "58.00 litres",
              grossVehicleWeight: null,
              luggageCapacitySeatsDown: "3 litres",
              bootspaceSeatsUp: "425 litres",
              vehicleWidthInclMirrors: null,
              maxLoadingWeight: null,
              standardFeatures: [
                {
                  description: "17in 5Spoke Alloy Wheels",
                  category: "Exterior",
                  __typename: "Feature",
                },
                {
                  description: "17in 5Spoke Split Alloy Wheels",
                  category: "Exterior",
                  __typename: "Feature",
                },
                {
                  description: "Drivers Seat manual height adjust",
                  category: "Interior",
                  __typename: "Feature",
                },
                {
                  description: "ES1- 7 Radio & Single CD & 7 Speakers",
                  category: "Audio and Communications",
                  __typename: "Feature",
                },
              ],
              chargingData: null,
              __typename: "TechData",
            },
            annualTax: {
              standardRate: 320,
              __typename: "AnnualTax",
            },
            oemDrivetrain: null,
            bikeLicenceType: null,
            derivative: "1.9 TiD Vector Sport Auto Euro 4 4dr",
            derivativeId: "cd7d9acf65ac43b0992c4374edc6a8df",
            __typename: "Specification",
          },
          stockType: "physical-stock",
          versionNumber: "18",
          tradeLifecycleStatus: "FORECOURT",
          condition: "Used",
          finance: null,
          locationArea: null,
          reservation: {
            status: null,
            eligibility: "NOT_ELIGIBLE",
            feeCurrency: "GBP",
            feeInFractionalUnits: 0,
            __typename: "AdvertReservation",
          },
          __typename: "Advert",
        },
        __typename: "Search",
      },
    },
  },
];
